module DPay
  class BlikRecurringRegistrationInfo
    attr_reader model: String?
    attr_reader frequency: String?
    attr_reader limit_amt: Integer?
    attr_reader tot_limit_amt: Integer?
    attr_reader limit_amt_fixed: bool?
    attr_reader init_date: String?
    attr_reader label: String?
    attr_reader registered_at: String?
    attr_reader raw: Hash[String, untyped]

    def self.from_api: (Hash[String, untyped] data) -> BlikRecurringRegistrationInfo

    def initialize: (Hash[String, untyped] data) -> void
  end
end
