module DPay
  class BlikRecurringRegistration
    MODELS: Array[String]
    FREQUENCY: Regexp
    DATE: Regexp

    @optional: Hash[String, untyped]

    def self.create: (String label, String model, String frequency) -> BlikRecurringRegistration

    def initialize: (String label, String model, String frequency) -> void
    def with_value: (Money value) -> self
    def with_limit_amt: (Integer limit_amt) -> self
    def with_tot_limit_amt: (Integer tot_limit_amt) -> self
    def with_limit_amt_fixed: (bool fixed) -> self
    def with_expiration_date: (String expiration_date) -> self
    def with_init_date: (String init_date) -> self
    def to_h: () -> Hash[String, untyped]

    private

    def assert_date: (untyped date) -> String
  end
end
