module DPay
  class ReturnUrls
    HTTP_URL: Regexp

    attr_reader success: String
    attr_reader fail: String
    attr_reader ipn: String?

    def initialize: (String success, String fail, ?String? ipn) -> void
  end
end
